version: "3.7"

services:
  backend-store:
    image: postgres:latest
    environment:
      - POSTGRES_USER=mlflow    
      - POSTGRES_PASSWORD=mlflow
      - POSTGRES_DB=mlflowdb
    ports:
      - 5433:5432   # Changed port to avoid conflict
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "5432", "-U", "mlflow", "-d", "mlflowdb"]
      interval: 5s
      timeout: 5s
      retries: 3

  minio:
    image: minio/minio
    volumes:
      - ./bucket_data:/data
    ports:
      - "9900:9900"  # Changed port to avoid conflict
      - "9901:9901"  # Changed port to avoid conflict
    environment:
      - MINIO_ROOT_USER=mlflow
      - MINIO_ROOT_PASSWORD=mlflow_pwd
    command: server /data --console-address ":9901" --address ":9900"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9900/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio-create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9900 mlflow mlflow_pwd &&
      if ! mc ls minio | grep --quiet mlflow; then
        mc mb minio/mlflow
      else
        echo 'bucket already exists'
      fi
      "

  tracking_server:
    build: .
    container_name: mlflow_server
    depends_on:
      - backend-store
      - minio-create-bucket
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=mlflow
      - AWS_SECRET_ACCESS_KEY=mlflow_pwd
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9900
      - MLFLOW_S3_IGNORE_TLS=true
    command: >
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@backend-store:5432/mlflowdb
      --host 0.0.0.0
      --serve-artifacts
      --artifacts-destination s3://mlflow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3


